//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_chng_password
    {
        public string id { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public int success_request_attempts { get; set; }
        public Nullable<int> is_expired { get; set; }
    
        public virtual auth auth { get; set; }
    }
}
