//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_req_forgot
    {
        public string id { get; set; }
        public string email { get; set; }
        public Nullable<int> pin { get; set; }
        public string token { get; set; }
        public Nullable<long> epoch_timestamp { get; set; }
        public Nullable<int> total_req_attempts { get; set; }
        public Nullable<int> req_attempts { get; set; }
        public Nullable<System.DateTime> last_attempt_timestamp { get; set; }
        public Nullable<int> is_expired { get; set; }
    }
}
