//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_req_verify
    {
        public string id { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public long epoch_timestamp { get; set; }
        public int total_req_attempts { get; set; }
        public int req_attempts { get; set; }
        public System.DateTime last_attempt_timestamp { get; set; }
        public int is_expired { get; set; }
    }
}
