//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auth> auths { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<promo_codes> promo_codes { get; set; }
        public virtual DbSet<auth_chng_password> auth_chng_password { get; set; }
        public virtual DbSet<auth_req_forgot> auth_req_forgot { get; set; }
        public virtual DbSet<promo_redemption_logs> promo_redemption_logs { get; set; }
        public virtual DbSet<social_service> social_service { get; set; }
        public virtual DbSet<social_orders> social_orders { get; set; }
        public virtual DbSet<referral_log> referral_log { get; set; }
        public virtual DbSet<auth_req_verify> auth_req_verify { get; set; }
        public virtual DbSet<account_referrer> account_referrer { get; set; }
    }
}
