//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_codes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promo_codes()
        {
            this.promo_redemption_logs = new HashSet<promo_redemption_logs>();
        }
    
        public string promocode { get; set; }
        public System.DateTime expiration_date { get; set; }
        public string discount_type { get; set; }
        public int discount_value { get; set; }
        public Nullable<int> usage_limit { get; set; }
        public Nullable<int> user_limit { get; set; }
        public int is_active { get; set; }
        public System.DateTime datecreated { get; set; }
        public string promocode_author { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promo_redemption_logs> promo_redemption_logs { get; set; }
    }
}
