//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_redemption_logs
    {
        public int log_id { get; set; }
        public string id { get; set; }
        public string promocode { get; set; }
        public long redemption_date_epoch { get; set; }
    
        public virtual auth auth { get; set; }
        public virtual promo_codes promo_codes { get; set; }
    }
}
