//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referral_log
    {
        public int log_id { get; set; }
        public string referrer_id { get; set; }
        public string referred_id { get; set; }
        public string referred_username { get; set; }
        public string referred_email { get; set; }
        public long epochtime { get; set; }
    }
}
