//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_service
    {
        public int service_id { get; set; }
        public string item { get; set; }
        public string item_desc { get; set; }
        public int rate { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<int> fast_lane_interval { get; set; }
        public Nullable<int> fast_lane_interval_rate { get; set; }
    }
}
