//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperTyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_orders
    {
        public long order_id { get; set; }
        public int service_id { get; set; }
        public string id { get; set; }
        public string item { get; set; }
        public int amount { get; set; }
        public double amount_in_coins { get; set; }
        public int isFastLane { get; set; }
    }
}
